# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('roll', models.PositiveIntegerField(unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('class_level', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
