# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


def set_default_academic_year(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    AcademicYear = apps.get_model('core', 'AcademicYear')
    default_year = AcademicYear.objects.order_by('-year').first()
    if not default_year:
        return
    Student.objects.filter(academic_year__isnull=True).update(academic_year=default_year)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('core', '0006_move_feature_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.academicyear'),
        ),
        migrations.RunPython(set_default_academic_year, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.academicyear'),
        ),
    ]
