# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('office', models.CharField(blank=True, max_length=120)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to='teachers.teacher')),
            ],
        ),
    ]
