# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, upload_to='notices/')),
            ],
        ),
    ]
