# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


def set_default_academic_year(apps, schema_editor):
    Classroom = apps.get_model('classrooms', 'Classroom')
    AcademicYear = apps.get_model('core', 'AcademicYear')
    default_year = AcademicYear.objects.order_by('-year').first()
    if not default_year:
        return
    Classroom.objects.filter(academic_year__isnull=True).update(academic_year=default_year)


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('core', '0006_move_feature_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='core.academicyear'),
        ),
        migrations.RunPython(set_default_academic_year, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('academic_year', 'class_level', 'section')},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='core.academicyear'),
        ),
    ]
