# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_move_role_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('class_test', 'Class Test'), ('semester_final', 'Semester Final')], max_length=20)),
                ('exam_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.semester')),
            ],
            options={
                'unique_together': {('semester', 'exam_type', 'exam_no')},
            },
        ),
    ]
