# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


def backfill_exam_dates(apps, schema_editor):
    Exam = apps.get_model('exams', 'Exam')
    for exam in Exam.objects.all():
        if not exam.date:
            exam.date = '2026-02-01'
        if not exam.start_time:
            exam.start_time = '09:00:00'
        if not exam.duration_minutes:
            exam.duration_minutes = 90
        exam.save(update_fields=['date', 'start_time', 'duration_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('classrooms', '0002_classroom_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classroom_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classrooms.classroomsubject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.RunPython(backfill_exam_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
