# Generated by Django 6.0.1 on 2026-02-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
        ('exams', '0002_exam_classroom_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to='admin_users.adminuser'),
        ),
        migrations.AddField(
            model_name='exam',
            name='syllabus',
            field=models.TextField(blank=True, default=''),
        ),
    ]
