# Generated by Django 6.0.1 on 2026-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatmessage_content_chatmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_code',
            field=models.CharField(blank=True, editable=False, max_length=14, null=True, unique=True),
        ),
    ]
