# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_move_role_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='core.subject')),
            ],
            options={
                'unique_together': {('class_level', 'section', 'subject', 'day_of_week', 'start_time')},
            },
        ),
    ]
