# Generated by Codex on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
