# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


def _copy_students(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    name=item.name,
                    roll=item.roll,
                    password_hash=item.password_hash,
                    class_level=item.class_level,
                    section=item.section,
                )
                for item in source_model.objects.all()
            ]
        )


def _copy_teachers(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    name=item.name,
                    email=item.email,
                    phone=item.phone,
                    department=item.department,
                    role=item.role,
                    password_hash=item.password_hash,
                )
                for item in source_model.objects.all()
            ]
        )


def _copy_admins(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    name=item.name,
                    email=item.email,
                    password_hash=item.password_hash,
                )
                for item in source_model.objects.all()
            ]
        )


def forward_copy(apps, schema_editor):
    CoreStudent = apps.get_model('core', 'Student')
    CoreTeacher = apps.get_model('core', 'Teacher')
    CoreAdminUser = apps.get_model('core', 'AdminUser')

    Student = apps.get_model('students', 'Student')
    Teacher = apps.get_model('teachers', 'Teacher')
    AdminUser = apps.get_model('admin_users', 'AdminUser')

    _copy_students(CoreStudent, Student)
    _copy_teachers(CoreTeacher, Teacher)
    _copy_admins(CoreAdminUser, AdminUser)


def reverse_copy(apps, schema_editor):
    CoreStudent = apps.get_model('core', 'Student')
    CoreTeacher = apps.get_model('core', 'Teacher')
    CoreAdminUser = apps.get_model('core', 'AdminUser')

    Student = apps.get_model('students', 'Student')
    Teacher = apps.get_model('teachers', 'Teacher')
    AdminUser = apps.get_model('admin_users', 'AdminUser')

    _copy_students(Student, CoreStudent)
    _copy_teachers(Teacher, CoreTeacher)
    _copy_admins(AdminUser, CoreAdminUser)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admin_user'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_copy, reverse_copy),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
