# Generated by Codex on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


def _copy_exams(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    semester_id=item.semester_id,
                    exam_type=item.exam_type,
                    exam_no=item.exam_no,
                )
                for item in source_model.objects.all()
            ]
        )


def _copy_notices(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    title=item.title,
                    description=item.description,
                    date=item.date,
                    pdf_file=item.pdf_file,
                )
                for item in source_model.objects.all()
            ]
        )


def _copy_routines(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    class_level=item.class_level,
                    section=item.section,
                    subject_id=item.subject_id,
                    day_of_week=item.day_of_week,
                    start_time=item.start_time,
                    end_time=item.end_time,
                )
                for item in source_model.objects.all()
            ]
        )


def _copy_attendance(source_model, target_model):
    if source_model.objects.exists() and not target_model.objects.exists():
        target_model.objects.bulk_create(
            [
                target_model(
                    id=item.id,
                    student_id=item.student_id,
                    subject_id=item.subject_id,
                    date=item.date,
                    status=item.status,
                )
                for item in source_model.objects.all()
            ]
        )


def forward_copy(apps, schema_editor):
    CoreExam = apps.get_model('core', 'Exam')
    CoreNotice = apps.get_model('core', 'Notice')
    CoreRoutine = apps.get_model('core', 'Routine')
    CoreAttendance = apps.get_model('core', 'Attendance')

    Exam = apps.get_model('exams', 'Exam')
    Notice = apps.get_model('notices', 'Notice')
    Routine = apps.get_model('routines', 'Routine')
    Attendance = apps.get_model('attendance', 'Attendance')

    _copy_exams(CoreExam, Exam)
    _copy_notices(CoreNotice, Notice)
    _copy_routines(CoreRoutine, Routine)
    _copy_attendance(CoreAttendance, Attendance)


def reverse_copy(apps, schema_editor):
    CoreExam = apps.get_model('core', 'Exam')
    CoreNotice = apps.get_model('core', 'Notice')
    CoreRoutine = apps.get_model('core', 'Routine')
    CoreAttendance = apps.get_model('core', 'Attendance')

    Exam = apps.get_model('exams', 'Exam')
    Notice = apps.get_model('notices', 'Notice')
    Routine = apps.get_model('routines', 'Routine')
    Attendance = apps.get_model('attendance', 'Attendance')

    _copy_exams(Exam, CoreExam)
    _copy_notices(Notice, CoreNotice)
    _copy_routines(Routine, CoreRoutine)
    _copy_attendance(Attendance, CoreAttendance)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_move_role_models'),
        ('notices', '0001_initial'),
        ('exams', '0001_initial'),
        ('routines', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_copy, reverse_copy),
        migrations.AlterField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
